name: GitHub Actions
on: [push]
jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build the project
      - run: npm run build
      - run: cd dist
      - run: ls -lat

