name: GitHub Actions
on: [push]
jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm i && npm run build
      - name: Check out dist folder
        uses: actions/checkout@v3
        with:
          path: 'dist'
      - run: ls -lat

